// Article: Choosing a brand colour. Metadata and sources in src/data/learnIndex.js.
//
// The ramp in the middle of this article is generated by generateTintScale()
// from src/utils/colors.js at the Colour Studio's own defaults, and every ratio
// in it comes from contrastRatio() — so the table cannot disagree with the tool
// that produces the same ramp. Every figure quoted in the prose around it is
// recomputed from the same functions by tests/unit/learn-figures.test.js,
// including the two theme grounds, which are read back out of
// src/styles/global.css rather than trusted.
//
// The two thresholds the article measures against are quoted from WCAG 2.2 with
// links to the clauses.

import { Aside, DataTable, Spec } from '../../components/LearnParts'
import BrandRampTable from '../../components/BrandRampTable'
import { contrastRatio, hslToHex } from '../../utils/colors'

const WCAG = 'https://www.w3.org/TR/WCAG22'
const LIGHT_GROUND = '#EFEEE9'

// Pure grey against the same HSL lightness pulled 8% and 16% towards the brand
// hue. Computed, because the claim under the table is that the first column and
// the last are close, and how close is the entire point.
const NEUTRAL_ROWS = [50, 40, 30].map((l) => {
  const grey = hslToHex(0, 0, l)
  const soft = hslToHex(221, 8, l)
  const strong = hslToHex(221, 16, l)
  return [
    `HSL lightness ${l}%`,
    `${grey.toUpperCase()} · ${contrastRatio(grey, LIGHT_GROUND).toFixed(2)}:1`,
    `${soft.toUpperCase()} · ${contrastRatio(soft, LIGHT_GROUND).toFixed(2)}:1`,
    `${strong.toUpperCase()} · ${contrastRatio(strong, LIGHT_GROUND).toFixed(2)}:1`,
  ]
})

export default function BrandColour() {
  return (
    <>
      <section id="jobs">
        <h2>One value, several jobs</h2>
        <p>
          A brand colour arrives as a single hex, and the interface immediately
          asks it to do four separate things: be a fill with a label on it, be a
          link in running text, be the border that identifies a focused input,
          and be a large flat area behind something else. Only the fourth has no
          contrast requirement attached.
        </p>

        <Spec
          source="WCAG 2.2 — SC 1.4.3 Contrast (Minimum)"
          href={`${WCAG}/#contrast-minimum`}
          level="Level AA"
        >
          The visual presentation of text and images of text has a contrast ratio
          of at least 4.5:1
        </Spec>

        <Spec
          source="WCAG 2.2 — SC 1.4.11 Non-text Contrast"
          href={`${WCAG}/#non-text-contrast`}
          level="Level AA"
        >
          The visual presentation of the following have a contrast ratio of at
          least 3:1 against adjacent color(s): <b>User Interface Components</b> —
          visual information required to identify user interface components and
          states, except for inactive components or where the appearance of the
          component is determined by the user agent and not modified by the
          author.
        </Spec>

        <p>
          Two numbers, and the pair each applies to is different every time. As a
          link, the brand colour is measured against the page ground. As a fill,
          it is measured against its own label — a different pair, and one where
          the brand colour is the background rather than the ink. As a border, it
          is measured against whatever is on both sides of it, at 3:1 rather than
          4.5:1.
        </p>
        <p>
          Because the ratio is symmetric — the formula takes the lighter and the
          darker luminance and does not care which is text — the first two look
          like the same test when the label is white and the ground is white.
          They stop being the same test the moment either changes, and one of
          them always does: the ground changes in the dark theme, and the label
          changes the first time a colour is too light to carry white.
        </p>
      </section>

      <section id="the-ramp">
        <h2>What the ramp is for</h2>
        <p>
          A ramp is not a set of decorative variants of the brand colour. It is
          the set of values the brand hue takes so that each of those jobs can be
          given a colour that passes its own test, while the hue stays constant
          and the identity survives.
        </p>

        <BrandRampTable />

        <p>
          Read the two ratio columns against each other rather than down their
          own length. On the light ground the first stop that clears 4.5:1 is
          600; on the dark ground the last one that does is 400. The window for
          text on light starts below the window for text on dark ends, and the
          two do not meet.
        </p>
      </section>

      <section id="no-single-stop">
        <h2>No single stop clears both grounds</h2>
        <p>
          Not one of the eleven stops in that ramp measures 4.5:1 against both{' '}
          <code>#EFEEE9</code> and <code>#101012</code>. Two of them —
          400 and 500 — clear 3:1 against both, which is why a brand-coloured
          border can be one value in a theme system while a brand-coloured link
          cannot.
        </p>
        <p>
          That is the arithmetic behind the rule the previous guide states
          structurally: a role token has to hold a different value per theme.
          It is not a stylistic preference for lighter accents on dark
          backgrounds. It is that the set of values satisfying the light
          constraint and the set satisfying the dark one have no member in
          common, so no single value can be chosen.
        </p>
        <p>
          The seed here is worth its own line. <code>#2563EB</code> measures
          4.45:1 against this product&rsquo;s light ground — five hundredths under
          the threshold, on the most-used blue on the web, against an off-white
          rather than a pure white. A brand colour that fails by that margin
          fails in a way no reviewer catches by eye, and the number is different
          again on <code>#FFFFFF</code>. Which ground the check was run against is
          part of the result.
        </p>
        <Aside>
          The stops here are the generator&rsquo;s <i>perceived</i> curve, which
          spaces them by perceptual tone rather than by HSL lightness. The linear
          curve produces a different ramp from the same seed, and therefore
          different stop numbers for the same jobs.
        </Aside>
      </section>

      <section id="neutrals">
        <h2>The neutral carries more of the screen than the brand colour</h2>
        <p>
          Most of an interface is neutral: grounds, surfaces, borders, body text,
          the disabled state of everything. The brand colour appears on a small
          fraction of the pixels, and it is the neutral ramp that decides whether
          the product looks like anything.
        </p>
        <p>
          A neutral does not have to be grey. Pulling it a few percent towards the
          brand hue ties the two together, and the cost in contrast is small
          enough to be spent freely.
        </p>

        <DataTable
          head={['Lightness', 'Pure grey', '8% towards hue 221', '16% towards hue 221']}
          numeric={[1, 2, 3]}
          rows={NEUTRAL_ROWS}
          caption={`Built with hslToHex() and measured with contrastRatio() against ${LIGHT_GROUND}, this page's light-theme ground. Saturation is the only variable; HSL lightness is held.`}
        />

        <p>
          Every one of those moves is under four tenths of a ratio point at 8%
          saturation and under seven tenths at 16% — and every one of them moves{' '}
          <i>upwards</i>, which is the detail worth keeping.
          Adding saturation at a fixed HSL lightness makes the colour darker in
          luminance, because HSL lightness is not luminance. A tinted neutral is
          therefore not a contrast risk relative to the grey it replaces; it is
          slightly safer, and any budget that was passing with the grey is still
          passing.
        </p>
      </section>

      <section id="state-collision">
        <h2>When the brand hue is already spoken for</h2>
        <p>
          Error, success and warning occupy three regions of the hue wheel that
          the reader has learnt elsewhere, and a brand colour that lands in one of
          them takes the meaning with it. The collision is closer than it looks
          on a swatch card: a brand red of <code>#E11D48</code> and an error red
          of <code>#DC2626</code> measure 1.03:1 against each other, which is to
          say they are the same colour as far as any contrast-based distinction
          is concerned.
        </p>
        <p>
          There are two honest resolutions and one that is not. The brand hue can
          move — a magenta rather than a red — or the state palette can be pushed
          away from it, which usually costs the state colours their conventional
          reading. What does not work is keeping both and relying on position to
          separate them, because that makes colour the only carrier of the
          difference at exactly the moment the difference matters.
        </p>

        <Spec
          source="WCAG 2.2 — SC 1.4.1 Use of Color"
          href={`${WCAG}/#use-of-color`}
          level="Level A"
        >
          Color is not used as the only visual means of conveying information,
          indicating an action, prompting a response, or distinguishing a visual
          element.
        </Spec>

        <p>
          1.4.1 is the criterion that makes the collision survivable rather than
          the one that forbids it. An error that carries an icon and a sentence
          is still an error when its red is the brand red; an error that is a red
          border on a field is not distinguishable from a brand-coloured focus
          ring, and was never distinguishable to a reader who does not see the
          hue at all.
        </p>
      </section>
    </>
  )
}
