// The type-scale article's live ladder.
//
// Built with buildFluidScale() from src/utils/fluidType.js — the same function
// the Type Scale Generator exports from — and the tool's own defaults, so the
// sizes here and the sizes it hands you are produced by one implementation.
//
// The specimen on each row carries the row's REAL clamp() as its font-size, so
// the ladder is not a picture of a scale: resize the window and it moves,
// because it is the same CSS the export contains. A table of numbers would
// have made the same claim without letting anyone check it.

import { buildFluidScale } from '../utils/fluidType'

// The Type Scale Generator's defaults, at both ends of the range. Written out
// rather than imported because they live in the page component's DEFAULTS
// object; the article says which numbers it used, and the caption states it.
const MOBILE = { base: 15, ratio: 1.2 }
const DESKTOP = { base: 16, ratio: 1.25 }
const NAMES = ['sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl']
const EXPS = [-1, 0, 1, 2, 3, 4, 5]

const SCALE = buildFluidScale({ mobile: MOBILE, desktop: DESKTOP, exps: EXPS, names: NAMES, round: 'half' })

export default function TypeLadder() {
  return (
    <figure className="lart-ladder-wrap">
      <ol className="lart-ladder">
        {SCALE.map((step) => (
          <li className="lart-ladder-row" key={step.name}>
            <span className="lart-ladder-name">{step.name}</span>
            <span className="lart-ladder-specimen" style={{ fontSize: step.css }} aria-hidden="true">
              Type that scales
            </span>
            <span className="lart-ladder-nums">
              <span>{step.minPx}px at 375</span>
              <span>{step.maxPx}px at 1440</span>
            </span>
          </li>
        ))}
      </ol>
      <figcaption className="lart-table-cap">
        Generated by <code>buildFluidScale()</code> from <code>src/utils/fluidType.js</code> at
        the Type Scale Generator&rsquo;s defaults — {DESKTOP.base}px base on a {DESKTOP.ratio} ratio at
        1440, {MOBILE.base}px on {MOBILE.ratio} at 375, rounded to the nearest half pixel. Each
        specimen carries its own row&rsquo;s <code>clamp()</code> as its font-size, so narrowing this
        window moves them.
      </figcaption>
    </figure>
  )
}
