// Which provider actually served a generation, said out loud.
//
// /api/ai has ALWAYS returned a `provider` field on generate-prompt responses,
// and both prompt tools destructured `prompt` and `platform` off the response
// and dropped it on the floor. That is why a dead OpenRouter was invisible: the
// Gemini fallback returns a perfectly good prompt, so the page, the toast, the
// quota meter and the user's own judgement all say "working" while the primary
// provider is gone. The only surface that disagreed was a devtools Network tab.
//
// This turns the field into something a person can see without opening
// devtools, which is the cheapest half of ai-failover-invisible and the whole
// of the founder verification procedure in docs/OWNER-ACTIONS.md — that register
// is local-only since 2026-09-16 and is not in this repository (.gitignore says
// why), so the procedure is named here rather than linked.
//
// It deliberately does NOT hide the healthy case. A badge that appears only on
// failure teaches nobody what the normal state looks like, so its absence would
// read as "no badge yet" rather than "something is wrong" — and it would be one
// refactor away from never rendering at all, silently, which is the exact fault
// class being fixed here.

const PROVIDERS = {
  openrouter: {
    label: 'OpenRouter',
    fallback: false,
    title: 'Generated by OpenRouter, the primary provider. This is the healthy state.',
  },
  gemini: {
    label: 'Gemini · fallback',
    fallback: true,
    title: 'OpenRouter did not answer, so this was generated by the Gemini fallback. Your prompt is fine — the primary provider is not. If this keeps appearing, the OpenRouter key is wrong, revoked, rate-limited or the service is down.',
  },
}

/**
 * Describe the `provider` field from an /api/ai generate-prompt response.
 *
 * Returns `null` when there is nothing to describe, so a caller can render
 * conditionally without inventing a label for an absent value. An unrecognised
 * provider is shown verbatim and treated as a fallback: a name this build does
 * not know about is, by definition, not the primary it was shipped with.
 */
export function describeProvider(provider) {
  if (!provider || typeof provider !== 'string') return null
  const known = PROVIDERS[provider]
  if (known) return { ...known, id: provider }
  return {
    id: provider,
    label: `${provider} · unrecognised`,
    fallback: true,
    title: `This build does not recognise "${provider}" as the primary provider. Either the server changed provider or the response shape did.`,
  }
}

/**
 * Inline style for the badge, keyed off the two semantic colour tokens that
 * already exist in both themes. Inline rather than a class because global.css is
 * being worked on by other people and a badge is not worth a merge conflict.
 */
export function providerBadgeStyle(described) {
  return {
    padding: '3px 10px',
    borderRadius: 'var(--radius)',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '.04em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    color: described.fallback ? 'var(--warn)' : 'var(--t2)',
    border: `1px solid ${described.fallback ? 'var(--warn)' : 'var(--border)'}`,
  }
}
