// DESIGN.md IS GENERATED. DO NOT HAND-EDIT THE FILE IT WRITES.
//
// Impeccable's `live` command refuses to boot without a DESIGN.md, and the
// official format makes its YAML frontmatter NORMATIVE — a token table.
//
// This repository had already declined one, for a recorded reason:
// docs/reference/doc-authority-map.md notes that EVERY doc table of design
// values here has drifted from the stylesheet at least once, so a hand-written
// DESIGN.md would be a fourth copy of values whose only trustworthy home is
// src/styles/global.css. The note left behind by that decision said a future
// command needing one should "record decisions and their reasons and still
// point at global.css for every value".
//
// So it is generated. Every value is READ from global.css; the prose carries
// the decisions. tests/unit/design-md-mirrors-css.test.js re-runs this
// generator and fails if the committed file differs — the same
// mirror-plus-drift-test pattern src/config/plans.js uses against
// api/_lib/plans.js, and src/config/planLadder.js against TRIAL_DAYS.
import fs from 'node:fs'
import path from 'node:path'

const CSS = path.join(process.cwd(), 'src/styles/global.css')

/** Custom properties declared directly inside one selector's block. */
function blockVars(css, selector) {
  const at = css.indexOf(selector + '{')
  const start = at >= 0 ? at : css.indexOf(selector + ' {')
  if (start < 0) throw new Error(`global.css has no ${selector} block`)
  const open = css.indexOf('{', start)
  const body = css.slice(open + 1, css.indexOf('}', open))
  return Object.fromEntries(
    [...body.matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+)/g)].map((m) => [m[1], m[2].trim()]),
  )
}

export function readTokens() {
  // Comments stripped first: several token blocks carry long notes containing
  // colons, and one of them writes `--font:` inside prose.
  const css = fs.readFileSync(CSS, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')
  return {
    root: blockVars(css, ':root'),
    light: blockVars(css, '[data-theme="light"]'),
    dark: blockVars(css, '[data-theme="dark"]'),
  }
}

const q = (v) => '"' + String(v).replace(/"/g, '\\"') + '"'

const COLOUR_MAP = [
  ['surface-ground', 'bg-0'], ['surface-raised', 'bg-1'], ['surface-sunken', 'bg-2'],
  ['card', 'card'], ['ink', 't0'], ['ink-muted', 't2'], ['ink-faint', 't3'],
  ['border', 'border'], ['border-strong', 'bh'],
  ['accent', 'accent'], ['accent-strong', 'accent-strong'], ['accent-on', 'accent-fg'],
  ['danger', 'err'], ['warning', 'warn'], ['success', 'ok'],
]

const RADII = ['radius-xs', 'radius-s', 'radius', 'radius-l', 'radius-xl', 'radius-2xl', 'radius-3xl', 'radius-pill']
const SPACE = ['s-1', 's-2', 's-3', 's-4', 's-5', 's-6', 's-7', 's-8', 's-9', 's-10']

export function renderDesignMd(t = readTokens()) {
  const { root, light, dark } = t
  // :root before dark. --accent-fg is declared once on :root and overridden only
  // in dark, so a light-then-dark fallback silently reported the DARK ink colour
  // as the light accent foreground.
  const colour = (key) => light[key] ?? root[key] ?? dark[key]
  const L = []
  const push = (...lines) => L.push(...lines)

  push('---')
  push('name: UIL4B')
  push('description: Browser-based tools for building and exporting UI and brand design kits.')
  push('colors:')
  for (const [slug, key] of COLOUR_MAP) {
    const v = colour(key)
    if (v) push('  ' + slug + ': ' + q(v) + '   # --' + key)
  }
  push('typography:')
  push('  display:')
  push('    fontFamily: ' + q(root.display))
  push('    fontSize: "clamp(46px, min(6.6vw, 9.5svh), 96px)"   # .home-hero-h1')
  push('    fontWeight: 800')
  push('    lineHeight: 0.98')
  push('    letterSpacing: "-0.045em"')
  push('  body:')
  push('    fontFamily: ' + q(root.display))
  push('    fontSize: "16px"')
  push('    fontWeight: 400')
  push('    lineHeight: 1.55')
  push('  mono:')
  push('    fontFamily: ' + q(root.mono))
  push('rounded:')
  for (const k of RADII) {
    if (root[k]) {
      const name = k === 'radius' ? 'base' : k.replace('radius-', '')
      // A YAML key beginning with a digit (2xl, 3xl) has to be quoted or the
      // parser is entitled to read it as a number.
      const safe = /^[0-9]/.test(name) ? q(name) : name
      push('  ' + safe + ': ' + q(root[k]) + '   # --' + k)
    }
  }
  push('spacing:')
  for (const k of SPACE) if (root[k]) push('  ' + k + ': ' + q(root[k]))
  push('---')
  push('')
  push('# UIL4B')
  push('')
  push('<!-- GENERATED by scripts/design-md.mjs from src/styles/global.css. Do not')
  push('     hand-edit: tests/unit/design-md-mirrors-css.test.js regenerates this file')
  push('     and fails on any difference. Change the value in global.css, then run')
  push('     `npm run design:md`. -->')
  push('')
  push('## Overview')
  push('')
  push('The stylesheet is the design system. `src/styles/global.css` holds every live')
  push('token value, and `docs/reference/design-language-v2.md` records the shipped V2')
  push('language with its founder-approved deviations. **This file is a generated')
  push('mirror, written because Impeccable needs a machine-readable token layer. It is')
  push('never the place to change a value.**')
  push('')
  push('Three surfaces, one system: Create (the tools), Discover (the libraries), Learn')
  push('(the articles). Continuity between them is a product property rather than a')
  push('nicety — the whole claim is that a designer does not have to leave to do the')
  push('next step.')
  push('')
  push('## Colors')
  push('')
  push('**Both themes are shipped surfaces**, three-state: Light / Dark / System. Every')
  push('new surface is checked in both, and `tests/user-sim/41-theme-control.spec.js`')
  push('holds it. The frontmatter carries the LIGHT values because the format takes one')
  push('set; the dark values sit beside them in `[data-theme="dark"]`.')
  push('')
  push('The accent is ' + colour('accent') + ' in light and ' + dark.accent + ' in dark, and it is the only')
  push('saturated colour in the interface. Everything else is a warm neutral ramp, so')
  push('anything accent-coloured is claiming to be the next action. Spend it accordingly.')
  push('')
  push('Accent-family text has an AA floor that is asserted rather than assumed:')
  push('`tests/user-sim/39-accent-contrast.spec.js` fails any accent text under it.')
  push('')
  push('## Typography')
  push('')
  push('One family does every job. Manrope for interface, headline and display; JetBrains')
  push('Mono for values, labels and anything a user copies. There is no third face.')
  push('')
  push('**The hero headline is sized by height as well as width** —')
  push('`clamp(46px, min(6.6vw, 9.5svh), 96px)` — because a laptop is wide and short, and')
  push('a width-only clamp let the headline take 46% of a 780px-tall screen. It now holds')
  push('a flat ~36%. This is the only headline on the site carrying a height term; the')
  push('others were measured and did not need one.')
  push('')
  push('## Layout')
  push('')
  push('Breakpoints are 380, 480, 640, 768, 860, 900 and 1180. Everything that must clear')
  push('the fixed nav derives from two tokens and never computes the offset by hand:')
  push('`--chrome-h` is nav-top + nav-h + notice-h, and `--nav-clear` is that plus 8px.')
  push('`tests/unit/notice-strip-reserves-height.test.js` fails on any hand-rolled copy,')
  push('because a rule that spells the offset out itself ends up under the notice strip')
  push('the moment one appears.')
  push('')
  push('## Shapes')
  push('')
  push('The radius ramp is in the frontmatter. Rounding is a user setting, stored under')
  push('`vs-appearance`, so no component may hard-code a radius — read the token, or the')
  push('setting does nothing.')
  push('')
  push("## Do's and Don'ts")
  push('')
  push('- **Do** change values in `src/styles/global.css` and regenerate this file.')
  push('- **Do** check both themes and reduced motion. All three ship.')
  push("- **Don't** hand-edit this file. The drift test fails and the edit is lost.")
  push("- **Don't** add a second copy of a design value to any document. Every doc table")
  push('  of design values in this repository has drifted from the stylesheet at least')
  push('  once, which is why this one is generated.')
  push("- **Don't** treat equal visual weight as neutral. Six equal cards for six unequal")
  push('  things is on the anti-slop tell list —')
  push('  `.claude/skills/uil4b-brand-design/references/anti-slop-quality-bar.md`.')
  push('')
  return L.join('\r\n') + '\r\n'
}

const invokedDirectly = process.argv[1] && process.argv[1].replace(/\\/g, '/').endsWith('scripts/design-md.mjs')
if (invokedDirectly) {
  fs.writeFileSync(path.join(process.cwd(), 'DESIGN.md'), renderDesignMd())
  console.log('DESIGN.md written from src/styles/global.css')
}
