// WHICH SHARE CARD EACH ROUTE UNFURLS AS.
//
// ── The gap ─────────────────────────────────────────────────────────────────
//
// scripts/prerender.mjs rewrites title, description, canonical, og:title,
// og:description, og:url, twitter:title and twitter:description per route — but
// not og:image or twitter:image. So all 28 shells pointed at the one card at
// /previews/og-image.png, and a link to the Contrast Checker posted in Slack
// looked exactly like a link to the homepage. The words were right and the
// picture was wrong, and the picture is the half people actually look at.
//
// ── The decision: one card per SECTION, not per route ───────────────────────
//
// Three options were on the table.
//
// PER-ROUTE ART, generated at build time from project data. The app does know
// its own palettes, gradients and type scales, so it could draw 28 distinct
// cards. The cost is not the drawing — it is that a share card is mostly TYPE,
// and rasterising type needs a real renderer. Node has no canvas; adding sharp
// or resvg means a native binary in the Vercel build for a picture. Making the
// build depend on Chromium is worse still: a browser download in CI, on the
// critical path of every deploy, to redraw seven images that change about twice
// a year.
//
// HAND-MADE CARDS for the few routes that matter. Cheapest to ship and the
// worst to maintain: it needs a designer for every new tool, and a tool that
// ships without one silently falls back to the homepage card — the exact
// failure being fixed, re-armed for every future route.
//
// ONE CARD PER SECTION — chosen. A tool page unfurling as its own CATEGORY
// closes most of the gap: a reader who sees "Colour" knows what the link is,
// which they did not when it said "Design Toolkit". It is 7 images rather than
// 28, every one drawn by the same generator from the same tokens, and a NEW
// TOOL INHERITS ITS SECTION'S CARD AUTOMATICALLY rather than falling back to
// the homepage. That last property is what settled it: the fallback for a route
// nobody thought about is its section, not the wrong picture.
//
// The cards are generated by `npm run og:cards` (scripts/og-cards.mjs, which is
// where the Chromium dependency lives) and committed, exactly like vercel.json
// is generated by `npm run sync:rewrites` and committed. Build-time cost: zero.
// tests/unit/share-cards.test.js fails if a card file is missing, if a route
// maps to nothing, or if the design tokens the cards were drawn from have moved
// since — which is the "committed artefact goes stale" failure that would
// otherwise be silent.
//
// ── Learn is a section since 2026-09-08 ─────────────────────────────────────
//
// /learn and every /learn/<slug> guide used to fall back to the homepage card,
// which the learn-content row in pipeline.js listed as a gap from the day the
// first guide shipped. The Learn card is drawn in the same system as the tool
// sections, and its subject is the section's real content: the guides, by the
// nav label each carries in learnIndex.js, and a blurb that COUNTS them. Both
// are derived from the registry rather than typed, and so are the routes — so
// a new guide inherits the card and, because cards.json records the guide
// list, fails tests/unit/share-cards.test.js until the card is redrawn with it.
//
// ── Nine routes deliberately keep the homepage card ────────────────────────
//
// /home IS the homepage, so the homepage card is the correct picture, not a
// fallback. The support and legal pages (/help, /info, /feedback, /privacy,
// /terms, /sitemap, /community) are site chrome rather than a product area;
// inventing a "Legal" card for them would be drawing seven images to say
// nothing. /seo is a real tool with no section of its own — flagged rather than
// forced into a category it does not belong to.
import { CREATE_GROUPS } from '../src/data/toolTree.js'
import { LEARN_ARTICLES, LEARN_ARTICLE_ROUTES, TOPICS } from '../src/data/learnIndex.js'

export const CARD_DIR = '/previews'

/** The card every route falls back to — and the RIGHT card for the homepage. */
export const DEFAULT_CARD = Object.freeze({
  id: 'og-image',
  file: 'og-image.png',
  alt: 'UI L4B Design Toolkit — colour, icon, emoji and imagery tools',
})

/**
 * The sections, in the order they are drawn.
 *
 * `hue` names a `--hue-*` custom property in src/styles/global.css; the
 * generator reads the real hex out of that file rather than restating it, so a
 * brand colour change moves the cards. `group` names a CREATE_GROUPS id, and
 * the tool names printed on a card are read from that group — a new tool
 * appears on its section's card the next time the cards are generated, with no
 * edit here.
 */
const listOf = (items) => items.length < 2
  ? items.join('')
  : `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`

/** "7 guides on colour, typography and accessibility" — every figure derived. */
export const learnBlurb = () =>
  `${LEARN_ARTICLES.length} guides on ${listOf(TOPICS.map((t) => t.toLowerCase()))}`

export const SECTIONS = Object.freeze([
  Object.freeze({
    id: 'colour',
    label: 'Colour',
    blurb: 'Palettes, tints, gradients and contrast',
    hue: 'colour',
    group: 'colour',
    // `/create/color` LEFT THIS LIST on 2026-09-18. It is no longer a page:
    // the colour landing was deleted with the Spectrum swap, so the route is a
    // 301 at the edge and gets no prerendered shell — a card pointed at it is a
    // card nobody can ever unfurl.
    routes: Object.freeze([
      '/create/palette', '/create/semantic-color',
      '/create/tint', '/create/gradient', '/create/contrast',
    ]),
  }),
  Object.freeze({
    id: 'type',
    label: 'Typography',
    blurb: 'Pair fonts and build scales that hold up',
    hue: 'type',
    group: 'type',
    routes: Object.freeze(['/create/font-gallery', '/create/font-pair', '/create/type-scale']),
  }),
  Object.freeze({
    id: 'icons',
    label: 'Icons & Emoji',
    blurb: '200,000 icons and every emoji, copy-ready',
    hue: 'icons',
    group: 'icons',
    routes: Object.freeze(['/create/icons', '/create/emoji']),
  }),
  Object.freeze({
    id: 'media',
    label: 'Imagery & Media',
    blurb: 'Convert, compress and measure',
    hue: 'imagery',
    group: 'imagery',
    routes: Object.freeze(['/create/file-converter', '/create/aspect-ratio', '/create/3d-converter']),
  }),
  Object.freeze({
    id: 'ai',
    label: 'AI Tools',
    blurb: 'Alt text and prompts, metered honestly',
    hue: 'ai',
    group: 'ai',
    routes: Object.freeze(['/create/alt-text']),
  }),
  Object.freeze({
    id: 'discover',
    label: 'Discover',
    blurb: 'Curated palettes, gradients and prompts',
    hue: 'component',
    group: null,
    tools: Object.freeze(['Palette Library', 'Gradient Library', 'Prompt Library']),
    routes: Object.freeze(['/discover', '/discover/palettes', '/discover/gradients', '/discover/prompts']),
  }),
  Object.freeze({
    id: 'plans',
    label: 'Plans',
    blurb: 'The whole toolkit is free. Pro adds room',
    hue: 'colour',
    group: null,
    tools: Object.freeze(['Free forever', 'Pro monthly', 'Pro yearly']),
    routes: Object.freeze(['/plans']),
  }),
  // Last so that railSections() still finds AI Tools first for --hue-ai:
  // Learn wears the hue the /learn landing paints its own cards with, and
  // like Plans it owns no band of its own on the homepage rail.
  Object.freeze({
    id: 'learn',
    label: 'Learn',
    eyebrow: 'Reference guides',
    blurb: learnBlurb(),
    hue: 'ai',
    group: null,
    tools: Object.freeze(LEARN_ARTICLES.map((a) => a.navLabel)),
    routes: Object.freeze(['/learn', ...LEARN_ARTICLE_ROUTES]),
  }),
])

/** The tool names printed on a section's card, from the app's own tree. */
export function toolNamesFor(section) {
  if (section.tools) return [...section.tools]
  const group = CREATE_GROUPS.find((g) => g.id === section.group)
  if (!group) return []
  // Only the tools that actually exist today — a card advertising a Soon tool
  // would promise a page that renders the workshop state.
  return group.tools.filter((t) => !t.soon).map((t) => t.label)
}

const norm = (p) => {
  const s = String(p || '/').split('?')[0].split('#')[0].toLowerCase()
  return s.length > 1 ? s.replace(/\/+$/, '') : s
}

const BY_ROUTE = new Map()
for (const section of SECTIONS) {
  for (const route of section.routes) BY_ROUTE.set(norm(route), section)
}

/**
 * The card a route unfurls as: `{ id, file, alt }`.
 *
 * Never throws and never returns nothing. A route nobody classified gets the
 * homepage card, which is what it would have got anyway — the point of this
 * function is that a route which HAS a section can no longer silently miss it.
 */
export function cardFor(pathname) {
  const section = BY_ROUTE.get(norm(pathname))
  if (!section) return DEFAULT_CARD
  return {
    id: section.id,
    file: `og-${section.id}.png`,
    alt: `UI L4B ${section.label} — ${section.blurb.toLowerCase()}`,
  }
}

/** Absolute URL for a card, which is what og:image requires. */
export const cardUrl = (origin, card) => `${origin}${CARD_DIR}/${card.file}`

/** Every card file the site references, for the "does it exist" test. */
export function allCardFiles() {
  return [DEFAULT_CARD.file, ...SECTIONS.map((s) => `og-${s.id}.png`)]
}
