// Generate public/sitemap.xml from the route matrix.
//
// ── Why this exists ─────────────────────────────────────────────────────────
//
// scripts/route-matrix.mjs decides which URLs get a crawlable shell, and its
// own header already names the sitemap as "the ADVERTISED SUBSET" of that
// matrix. It was a subset kept by hand, which meant the one file we point
// Google at was the only part of the routing story nothing generated.
//
// Two things followed from that, and only one of them was caught.
//
// The URL SET was in fact well guarded — prerender-routes.test.js asserts
// containment, redirects.test.js asserts every live Create tool appears and no
// Soon one does. What NOTHING checked was everything else in the file, because
// sitemapRoutes() parses `<loc>` and keeps only the pathname:
//
//   · the ORIGIN in each `<loc>` was never read, so an entry pointing at
//     http://uil4b.com (no www, no TLS — a different site to a crawler) would
//     have passed every test;
//   · `/` was dropped by the parser before any assertion saw it, so the
//     homepage could have vanished from the sitemap silently;
//   · a duplicated entry was de-duplicated by the parser, so it could not fail;
//   · and the per-URL hints were pure hand-kept data that had already rotted —
//     every Create tool claimed `lastmod` 2026-08-22 through #325, #332 and the
//     locale pass, and `/` claimed 2026-07-28.
//
// ── Why the generated file carries no priority, changefreq or lastmod ───────
//
// Deliberate, and the reason is the same one that put this file here.
//
// Google has said publicly and repeatedly that it ignores `priority` and
// `changefreq`. They are decoration: two hand-kept numbers per URL that no
// consumer reads, on a file whose entire problem was hand-kept data.
//
// `lastmod` is different — Google DOES use it, but only where it judges the
// values honest, and ours were not. They were typed once and never touched
// again while the pages behind them changed. A date that says a tool has not
// moved since August, on the release that moved it, is worse than saying
// nothing: it teaches the crawler to distrust the field. There is no honest
// derived value available here either — a git timestamp would rewrite the file
// on every commit and a build stamp would claim every page changed today — so
// the field is dropped rather than faked.
//
// What is left is what a sitemap is actually for: the list of URLs we are
// asking to have crawled. Every byte of it is derived.
//
// Run via `npm run sync:sitemap`. tests/unit/prerender-routes.test.js fails the
// build if the file on disk and this generator ever disagree, the same way it
// already does for vercel.json.
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { prerenderRoutes } from './route-matrix.mjs'
import { canonicalUrl } from '../src/utils/routeMeta.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// Taken from routeMeta.js rather than written down again. canonicalUrl() is the
// function App.jsx stamps into every page head and prerender.mjs writes into
// every shell; a second copy of the origin here is how a sitemap ends up
// advertising a hostname the canonical tags disown.
export const ORIGIN = canonicalUrl('/').replace(/\/$/, '')

/**
 * The advertised subset of the matrix.
 *
 * Two rules, both derived:
 *
 *   1. `/` is advertised and is NOT in the matrix. The matrix excludes it
 *      because dist/index.html is served directly rather than prerendered into
 *      a sub-directory — an implementation detail of the build, and no reason
 *      to stop telling Google about the homepage.
 *
 *   2. Everything else must be prerendered AND its own canonical. `/home` is
 *      the case that rule exists for: it is prerendered so the site's
 *      most-linked URL stops unfurling as "Page not found", and routeMeta.js
 *      canonicalises it onto `/`, so advertising it would be asking Google to
 *      crawl a URL we have already disowned. Asking canonicalUrl() rather than
 *      naming /home keeps that true for the next alias as well.
 */
export function advertisedRoutes() {
  return [
    '/',
    ...prerenderRoutes().filter((route) => canonicalUrl(route) === `${ORIGIN}${route}`),
  ]
}

export function buildSitemap(routes = advertisedRoutes()) {
  const body = routes.map((route) => `  <url><loc>${ORIGIN}${route}</loc></url>`).join('\n')
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- GENERATED by scripts/sync-sitemap.mjs from the route matrix. Do not edit:',
    '     run `npm run sync:sitemap`. See that file for why there is no priority,',
    '     changefreq or lastmod. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    body,
    '</urlset>',
    '',
  ].join('\n')
}

// Run directly (not when imported by the test, which only wants the helpers).
if (process.argv[1]?.endsWith('sync-sitemap.mjs')) {
  const routes = advertisedRoutes()
  await writeFile(path.join(root, 'public', 'sitemap.xml'), buildSitemap(routes), 'utf8')
  console.log(`sync:sitemap — wrote ${routes.length} advertised URLs to public/sitemap.xml`)
}
