// DESIGN.md IS A GENERATED MIRROR, AND THIS IS WHAT STOPS IT BECOMING A LIE.
//
// Impeccable's `live` command will not boot without a DESIGN.md, and the format
// makes its YAML frontmatter NORMATIVE — a table of colours, type, radii and
// spacing. This repository had already declined to keep one, and the reason is
// recorded in docs/reference/doc-authority-map.md: **every doc table of design
// values here has drifted from the stylesheet at least once.** A hand-written
// DESIGN.md would be the fourth copy of values whose only trustworthy home is
// src/styles/global.css.
//
// So it is generated by scripts/design-md.mjs and this test regenerates it and
// compares byte for byte. The failure mode it exists to catch is not someone
// editing DESIGN.md — it is someone changing a colour in global.css and leaving
// DESIGN.md quoting the old one, at which point an agent reading DESIGN.md
// designs against a palette the product no longer has, and nothing anywhere
// reports a problem.
//
// This is the same mirror-plus-drift-test shape the repository already uses in
// two other places where a fact genuinely has to exist twice:
// tests/unit/plan-limits.test.js pins src/config/plans.js to api/_lib/plans.js,
// and tests/unit/trial-cadence.test.js pins the client ladder to the server's
// TRIAL_DAYS.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { renderDesignMd, readTokens } from '../../scripts/design-md.mjs'

const root = process.cwd()
const committed = () => fs.readFileSync(path.join(root, 'DESIGN.md'), 'utf8')

test('DESIGN.md is exactly what the generator produces from global.css', () => {
  // THE WHOLE POINT. Any drift — a changed token, a hand edit, a stale
  // regeneration — fails here with the first differing line named.
  const expected = renderDesignMd()
  const actual = committed()
  if (actual !== expected) {
    const a = actual.split('\r\n')
    const b = expected.split('\r\n')
    const i = a.findIndex((line, n) => line !== b[n])
    assert.fail(
      'DESIGN.md is out of date with src/styles/global.css. Run `npm run design:md`.\n'
      + `  first difference at line ${i + 1}\n`
      + `  committed: ${JSON.stringify(a[i])}\n`
      + `  generated: ${JSON.stringify(b[i])}`,
    )
  }
})

test('every colour in the frontmatter is a value global.css actually declares', () => {
  // A SECOND ROUTE TO THE SAME FACT, because the test above compares the file
  // to the generator and would keep passing if the GENERATOR started inventing
  // values. This one goes to the stylesheet independently.
  const { root: rootVars, light, dark } = readTokens()
  const declared = new Set(
    [rootVars, light, dark].flatMap((block) => Object.values(block)).map((v) => v.toLowerCase()),
  )
  const frontmatter = committed().split('---')[1] || ''
  const colours = [...frontmatter.matchAll(/^ {2}[a-z-]+: "([^"]+)" {3}# --([a-z0-9-]+)$/gm)]
  assert.ok(colours.length >= 10, `only ${colours.length} annotated tokens parsed out of the frontmatter`)

  const invented = colours
    .filter(([, value]) => !declared.has(value.toLowerCase()))
    .map(([, value, token]) => `${value} (claimed to be --${token})`)
  assert.deepEqual(invented, [], 'DESIGN.md quotes a value that appears nowhere in global.css')
})

test('each frontmatter colour matches the token it names', () => {
  // Stronger than the test above: not merely "this value exists somewhere in
  // the stylesheet" but "this value is what THAT token resolves to". A mapping
  // that pointed `accent` at the border colour would pass the previous test.
  const { root: rootVars, light, dark } = readTokens()
  const resolve = (key) => light[key] ?? rootVars[key] ?? dark[key]
  const frontmatter = committed().split('---')[1] || ''
  const wrong = []
  for (const [, value, token] of frontmatter.matchAll(/^ {2}[a-z-]+: "([^"]+)" {3}# --([a-z0-9-]+)$/gm)) {
    const actual = resolve(token)
    if (actual && actual.toLowerCase() !== value.toLowerCase()) {
      wrong.push(`--${token} is ${actual}, DESIGN.md says ${value}`)
    }
  }
  assert.deepEqual(wrong, [])
})

test('the light theme is what is published, not the dark one', () => {
  // POSITIVE CONTROL for the resolution order, and a real bug caught while
  // writing this: --accent-fg is declared once on :root and overridden only
  // under [data-theme="dark"], so a light-then-dark fallback published the DARK
  // ink colour as the light accent foreground — #101012 instead of #ffffff. The
  // frontmatter looked plausible and was wrong.
  const { root: rootVars, light, dark } = readTokens()
  assert.ok(!light['accent-fg'], 'light now declares --accent-fg; this control no longer proves the order')
  assert.ok(rootVars['accent-fg'], ':root no longer declares --accent-fg')
  assert.notEqual(rootVars['accent-fg'], dark['accent-fg'], 'root and dark agree, so the order cannot be tested here')
  assert.match(committed(), /accent-on: "#ffffff"/, 'the dark accent foreground is being published as the light one')
})

test('the generator reads the stylesheet rather than carrying its own copy', () => {
  // SOURCE ASSERTION. Everything above would still pass if the generator held a
  // hard-coded token table, which is exactly the thing this whole arrangement
  // exists to avoid.
  const src = fs.readFileSync(path.join(root, 'scripts/design-md.mjs'), 'utf8')
  assert.match(src, /src\/styles\/global\.css/, 'the generator no longer names the stylesheet')
  assert.match(src, /readFileSync/, 'the generator no longer reads a file')
  const hexes = src.match(/#[0-9a-fA-F]{6}\b/g) || []
  assert.deepEqual(hexes, [], `the generator has ${hexes.length} hard-coded colour(s) in it: ${hexes.join(', ')}`)
})
