// Founder request, 2026-09-03: "the pallete page should auto load a random
// pallete on the default free settings. reset should reset the settings to
// default but randomise the colour."
//
// Two rules in here are load-bearing, and both are the kind that fail silently:
//
//   THE DEFAULT MUST BE A FREE CONFIGURATION. A default that drifts onto a paid
//   system is a paywall bug, not a cosmetic one — it shows a free user output
//   they cannot themselves produce. Before this work, both the arrival board
//   and Reset ran `generateHarmony(seed, 'analogous')` while the system chip
//   read "Auto", and Analogous is `free: false`.
//
//   A SHARED LINK MUST BEAT THE RANDOM DRAW. Someone sends a palette to a
//   colleague; if the page randomises over it, their work is gone. This is the
//   layer where that can be enumerated rather than sampled.
//
// Randomness note: nothing here pins a colour. A test that asserted a specific
// hex out of a random draw would be flaky by construction, so these assert the
// PROPERTY — a palette is present, the settings are the free ones, the shared
// colours survived verbatim.
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {
  colorsFromSearch, defaultPaletteBoard, DEFAULT_SYSTEM, initialPaletteBoard, isDefaultSettings,
} from '../../src/utils/paletteDefaults.js'
import { COLOUR_SYSTEMS, FREE_COLOUR_SYSTEMS } from '../../src/config/colourSystems.js'
import { ZERO_ADJUST } from '../../src/utils/paletteAdjust.js'

const read = (p) => fs.readFileSync(path.join(process.cwd(), p), 'utf8')
const BUILDER = read('src/pages/PaletteBuilder.jsx')

const HEX = /^#[0-9a-f]{6}$/i
const isPalette = (colors) => Array.isArray(colors)
  && colors.length >= 5
  && colors.every((c) => HEX.test(c))

// ── The free-settings default ───────────────────────────────────────────────

test('the default system is one a free user can actually run', () => {
  const system = COLOUR_SYSTEMS.find((s) => s.id === DEFAULT_SYSTEM)
  assert.ok(system, `${DEFAULT_SYSTEM} is not a colour system this app knows`)
  assert.equal(system.free, true, `${DEFAULT_SYSTEM} is the default but is a PAID system`)
  assert.ok(FREE_COLOUR_SYSTEMS.includes(DEFAULT_SYSTEM))
})

test('the builder\'s own free list agrees — the gate that actually holds', () => {
  // config/colourSystems.js is documented as a MIRROR; the list inside
  // PaletteBuilder is what the collapse gate reads. If the default is free in
  // the mirror but not in the builder, a free user gets silently collapsed out
  // of the page's own default.
  const free = /const FREE_SYSTEMS = \[([^\]]*)\]/.exec(BUILDER)?.[1]
  assert.ok(free, 'FREE_SYSTEMS moved — this pin needs rewriting, not deleting')
  assert.ok(free.includes(`'${DEFAULT_SYSTEM}'`), `${DEFAULT_SYSTEM} is the default but is not in FREE_SYSTEMS`)
})

test('no paid system is left as a fallback in the builder', () => {
  // The same rule free-tier-gates.test.js already holds ColorStudio to. Five
  // `|| 'analogous'` fallbacks survived here — every one of them the "no system
  // recorded" case, which is exactly the default.
  assert.ok(!/\|\| 'analogous'/.test(BUILDER), 'a paid system is still a fallback default')
  assert.ok(!/generateHarmony\((?:fromSeed|firstSeed|DEFAULT_SEED), 'analogous'\)/.test(BUILDER),
    'a default board is still generated by the paid harmony engine')
})

test('a fresh board is a real palette on the default free settings', () => {
  for (let i = 0; i < 200; i += 1) {
    const board = defaultPaletteBoard()
    assert.ok(isPalette(board.colors), `draw ${i} produced ${JSON.stringify(board.colors)}`)
    assert.equal(board.system, DEFAULT_SYSTEM)
    assert.deepEqual(board.adjust, { ...ZERO_ADJUST })
    assert.equal(board.seed, board.colors[0])
  }
})

test('a fresh board is actually random, not a fixed seed', () => {
  // The property, not a value: 40 draws must not all be the same board. The
  // odds of a genuine randomiser failing this are vanishing; the odds of a
  // regression to a constant seed failing it are 1.
  const seen = new Set()
  for (let i = 0; i < 40; i += 1) seen.add(defaultPaletteBoard().colors.join(','))
  assert.ok(seen.size > 1, 'every draw produced the same board — the default is not random')
})

test('the draw comes from the injected randomiser, so there is only one', () => {
  // The Randomise button and the Space key run randomSystemPalette. If a second
  // source of randomness ever appears, this stops seeing the stub.
  const calls = []
  const stub = (system) => {
    calls.push(system)
    return ['#112233', '#223344', '#334455', '#445566', '#556677']
  }
  const board = defaultPaletteBoard(stub)
  assert.deepEqual(calls, [DEFAULT_SYSTEM])
  assert.equal(board.colors[0], '#112233')
})

test('an engine that throws still yields a board, never a blank one', () => {
  const board = defaultPaletteBoard(() => { throw new Error('solver died') })
  assert.ok(isPalette(board.colors))
  assert.equal(board.system, DEFAULT_SYSTEM)
})

// ── A shared link beats the random draw ─────────────────────────────────────

test('an explicit ?c= wins over a hand-off, a saved project and the draw', () => {
  const shared = ['#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF']
  const board = initialPaletteBoard({
    queryColors: shared,
    handoff: { colors: ['#111111', '#222222', '#333333'] },
    saved: { colors: ['#AAAAAA', '#BBBBBB', '#CCCCCC'], adjust: { h: 5, s: 5, b: 5, temp: 5 } },
  }, () => { throw new Error('the randomiser must not be reached') })
  assert.equal(board.source, 'query')
  assert.deepEqual(board.colors, shared)
  assert.equal(board.seed, shared[0])
  // A shared link carries finished colours, so the lens opens at zero rather
  // than re-applying whatever this device last left on.
  assert.deepEqual(board.adjust, { ...ZERO_ADJUST })
})

test('every other source in turn also beats the draw', () => {
  const randomiser = () => { throw new Error('the randomiser must not be reached') }

  const handoff = initialPaletteBoard({ handoff: { colors: ['#111111', '#222222', '#333333'] } }, randomiser)
  assert.equal(handoff.source, 'handoff')
  assert.deepEqual(handoff.colors, ['#111111', '#222222', '#333333'])

  const savedAdjust = { h: 5, s: -5, b: 0, temp: 0 }
  const saved = initialPaletteBoard({ saved: { colors: ['#AAAAAA', '#BBBBBB'], adjust: savedAdjust } }, randomiser)
  assert.equal(saved.source, 'saved')
  // The saved lens is carried, unlike the shared-link case.
  assert.deepEqual(saved.adjust, savedAdjust)
})

test('only a genuinely empty arrival draws', () => {
  // Each of these is a malformed source, not a real one — a single colour is
  // not a palette. They must fall THROUGH to the draw rather than render a
  // one-column board.
  for (const sources of [
    {},
    { queryColors: null, handoff: null, saved: null },
    { queryColors: [] },
    { queryColors: ['#FF0000'] },
    { handoff: { colors: ['#FF0000'] } },
    { saved: { colors: [] } },
  ]) {
    const board = initialPaletteBoard(sources)
    assert.equal(board.source, 'random', `${JSON.stringify(sources)} should have drawn`)
    assert.ok(isPalette(board.colors))
  }
})

test('the ?c= parser takes shared palettes and refuses everything else', () => {
  assert.deepEqual(colorsFromSearch('?c=FF0000,00FF00,0000FF'), ['#FF0000', '#00FF00', '#0000FF'])
  assert.deepEqual(colorsFromSearch('?c=ff0000,00ff00'), ['#FF0000', '#00FF00'])
  // Capped, so a hostile link cannot build a board of slivers.
  assert.equal(colorsFromSearch(`?c=${Array(30).fill('FF0000').join(',')}`, 10).length, 10)
  // One colour is not a shared palette — it must not beat the draw.
  assert.equal(colorsFromSearch('?c=FF0000'), null)
  assert.equal(colorsFromSearch('?c='), null)
  assert.equal(colorsFromSearch('?c=nonsense,alsonot'), null)
  assert.equal(colorsFromSearch('?other=1'), null)
  assert.equal(colorsFromSearch(''), null)
  assert.equal(colorsFromSearch(undefined), null)
})

// ── Reset ───────────────────────────────────────────────────────────────────

test('reset detects default SETTINGS, not a default board', () => {
  // Reset now draws a new colour every press, so no two resets share a board.
  // Comparing whole boards could never be true again, which would have quietly
  // killed the guard that stops a double-click overwriting the pre-reset
  // snapshot. Settings are the idempotent half.
  const atDefault = {
    harmony: DEFAULT_SYSTEM, locked: [], adjust: { ...ZERO_ADJUST },
    vision: 'normal', showContrast: false, importedGalleryId: null,
  }
  assert.equal(isDefaultSettings(atDefault), true)
  // …and it stays true across two different random boards.
  assert.equal(isDefaultSettings({ ...atDefault, colors: defaultPaletteBoard().colors }), true)
  assert.equal(isDefaultSettings({ ...atDefault, colors: defaultPaletteBoard().colors }), true)

  assert.equal(isDefaultSettings({ ...atDefault, harmony: 'triadic' }), false)
  assert.equal(isDefaultSettings({ ...atDefault, locked: [0] }), false)
  assert.equal(isDefaultSettings({ ...atDefault, adjust: { h: 10, s: 0, b: 0, temp: 0 } }), false)
  assert.equal(isDefaultSettings({ ...atDefault, vision: 'protanopia' }), false)
  assert.equal(isDefaultSettings({ ...atDefault, showContrast: true }), false)
  assert.equal(isDefaultSettings({ ...atDefault, importedGalleryId: 'g1' }), false)
})

test('reset rebuilds the board from the shared default, not its own generator', () => {
  // If Reset ever grows a second source of randomness it will drift from the
  // arrival draw and from the Randomise button, and the three will disagree
  // about what "default" means.
  assert.match(BUILDER, /const fresh = defaultPaletteBoard\(\)/)
  assert.match(BUILDER, /setHarmony\(DEFAULT_SYSTEM\)/)
  assert.ok(!/setSeed\(DEFAULT_SEED\)/.test(BUILDER), 'Reset still returns to the fixed seed')
})
